export const ON_NOTIFICATION_SUCCESS_INIT = 'ON_NOTIFICATION_SUCCESS_INIT';
export const ON_NOTIFICATION_WARNING_INIT = 'ON_NOTIFICATION_WARNING_INIT';
export const ON_NOTIFICATION_ERROR_INIT = 'ON_NOTIFICATION_ERROR_INIT';
export const ON_NOTIFICATION_CLOSE = 'ON_NOTIFICATION_CLOSE';

export const NOTIFICATION_TYPES = {
  SUCCESS: 1,
  WARNING: 2,
  ERROR: 3,
};
