export const CHECK_USER_INIT = 'CHECK_USER_INIT';
export const CHECK_USER_SUCCESS = 'CHECK_USER_SUCCESS';
export const CHECK_USER_FAILURE = 'CHECK_USER_FAILURE';
export const EXIT_USER = 'EXIT_USER';

export const FIND_REPORTS_INIT = 'FIND_REPORTS_INIT';
export const FIND_REPORTS_SUCCESS = 'FIND_REPORTS_SUCCESS';
export const FIND_REPORTS_FAILURE = 'FIND_REPORTS_FAILURE';

export const REMOVE_USER_INIT = 'REMOVE_USER_INIT';
export const REMOVE_USER_SUCCESS = 'REMOVE_USER_SUCCESS';
export const REMOVE_USER_FAILURE = 'REMOVE_USER_FAILURE';

export const CHANGE_REPORTS_SEARCH_CRITERIA = 'CHANGE_REPORTS_SEARCH_CRITERIA';
