export const GET_REVIEWS_INIT = 'GET_REVIEWS_INIT';
export const GET_REVIEWS_SUCCESS = 'GET_REVIEWS_SUCCESS';
export const GET_REVIEWS_ERROR = 'GET_REVIEWS_ERROR';

export const SAVE_REVIEWS_INIT = 'SAVE_REVIEWS_INIT';
export const SAVE_REVIEWS_SUCCESS = 'SAVE_REVIEWS_SUCCESS';
export const SAVE_REVIEWS_ERROR = 'SAVE_REVIEWS_ERROR';

